const projects = [
  {
    id: 4,
    open: false,
    title: 'Pomodoro Timer',
    tech: ['ReactJS'],
    imageUrl: '/pomodoro-t.png',
    demo: 'https://pomodo-timer.netlify.app/',
    source: 'https://github.com/ThashmilaJayasinghe/pomodoro-timer',
  },
  {
    id: 3,
    open: false,
    title: 'Recipe Management App with JWT Authentication',
    tech: ['ReactJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'JWT'],
    imageUrl: '/recipe-t.png',
    demo: 'https://recipe-app-dt8d.onrender.com',
    source: 'https://github.com/ThashmilaJayasinghe/Recipe-App',
  },
  {
    id: 5,
    open: false,
    title: 'Pac-Man Game',
    tech: ['HTML', 'CSS', 'JavaScript'],
    imageUrl: '/pacman-t.png',
    demo: 'https://pac-manjs.netlify.app/',
    source: 'https://github.com/ThashmilaJayasinghe/Pac-Man',
  },
  {
    id: 1,
    open: false,
    title: 'Supply-Demand Management for Agri Products',
    tech: ['ReactJS', 'NodeJS', 'ExpressJS', 'MongoDB'],
    imageUrl: '/agri-t.png',
    demo: null,
    source: 'https://github.com/ThashmilaJayasinghe/AgriDemandPlanning_SER058',
  },
  {
    id: 2,
    open: false,
    title: 'Mobile App to combat Intimate Partner Violence',
    tech: ['React Native', 'NodeJS', 'ExpressJS', 'MongoDB'],
    imageUrl: '/ipv-t.png',
    demo: null,
    source: 'https://github.com/SubodaDabarera/Intimate_Partner_Violence-MobileApp',
  },
  {
    id: 6,
    open: false,
    title: 'Expert System for Early Childhood Development through Music',
    tech: ['Python', 'Tensorflow', 'Jupyter Notebook', 'React Native', 'Google Cloud Platform'],
    imageUrl: '/research-t.png',
    demo: null,
    source: null,
  },
]

export default projects;